# Generated by Django 4.2.3 on 2023-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user_created_at', models.CharField(max_length=200, null=True)),
                ('random', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('id_no', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('invono', models.CharField(max_length=200, null=True)),
                ('date_joined', models.DateField(auto_now=True)),
                ('id_document', models.ImageField(max_length=200, null=True, upload_to='')),
                ('pin_document', models.ImageField(max_length=200, null=True, upload_to='')),
                ('registration_document', models.ImageField(max_length=200, null=True, upload_to='')),
                ('l_document', models.ImageField(max_length=200, null=True, upload_to='')),
                ('business_document', models.ImageField(max_length=200, null=True, upload_to='')),
                ('location_document', models.ImageField(max_length=200, null=True, upload_to='')),
                ('other_document', models.ImageField(max_length=200, null=True, upload_to='')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
