# Generated by Django 5.0.1 on 2024-01-10 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agents_records",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agents_records",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.expense_description",
            ),
        ),
        migrations.AddField(
            model_name="masterlist",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="stockout",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="temp",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="templist",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branches",
            ),
        ),
        migrations.AddField(
            model_name="templist",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
        migrations.AddField(
            model_name="temp",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
        migrations.AddField(
            model_name="stockout",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
        migrations.AddField(
            model_name="narations",
            name="vendor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
        migrations.AddField(
            model_name="masterlist",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
        migrations.AddField(
            model_name="accessory",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
    ]
