# Generated by Django 4.2.3 on 2023-09-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('conditions', models.CharField(max_length=200, null=True)),
                ('gen', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('serialno', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('cpu', models.CharField(max_length=200, null=True)),
                ('speed', models.CharField(max_length=200, null=True)),
                ('ram', models.CharField(max_length=200, null=True)),
                ('hdd', models.CharField(max_length=200, null=True)),
                ('screen', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('daterecieved', models.DateField(null=True)),
                ('daterepaired', models.DateField(null=True)),
                ('datedelivered', models.DateField(null=True)),
                ('qty', models.CharField(max_length=200, null=True)),
                ('total', models.CharField(max_length=200, null=True)),
                ('delvno', models.CharField(max_length=200, null=True)),
                ('dels', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('checked_by', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
