# Generated by Django 4.2.5 on 2023-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_templist_sub_total_alter_templist_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='terms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templist',
            name='terms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='templist',
            name='daterecieved',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
