# Generated by Django 4.2.5 on 2023-10-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_stockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user_created_at', models.CharField(max_length=200, null=True)),
                ('random', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('id_no', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('invono', models.CharField(max_length=200, null=True)),
                ('d_type', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dcustomer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('vendor', models.CharField(max_length=200, null=True)),
                ('customer', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('id_no', models.CharField(max_length=200, null=True)),
                ('document', models.CharField(max_length=200, null=True)),
                ('ref', models.CharField(max_length=200, null=True)),
                ('random', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('delvnote', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('invono', models.CharField(max_length=200, null=True)),
                ('total', models.IntegerField()),
                ('sold_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-date'],
            },
        ),
    ]
