# Generated by Django 4.2.5 on 2023-11-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_dcustomer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='templist',
            name='d_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
