# Generated by Django 4.2.5 on 2023-11-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
