# Generated by Django 4.2.5 on 2023-11-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_temp_is_active_templist_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='random',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='random',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='random',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templist',
            name='random',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
