# Generated by Django 4.2.5 on 2023-11-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_masterlist_random_stockout_random_temp_random_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
