# Generated by Django 4.2.5 on 2023-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_masterlist_brand_stockout_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='gen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='gen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
