# Generated by Django 4.2.5 on 2023-11-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_masterlist_gen_stockout_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='speed',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='speed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
