# Generated by Django 4.2.5 on 2023-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_masterlist_speed_stockout_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='screen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='screen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
