# Generated by Django 4.2.5 on 2023-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_masterlist_screen_stockout_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
