# Generated by Django 4.2.5 on 2023-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_dcustomer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
