# Generated by Django 4.2.5 on 2023-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_amount_product_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='datedelivered',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='datedelivered',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='datedelivered',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='templist',
            name='datedelivered',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='daterecieved',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
