# Generated by Django 4.2.5 on 2023-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_narations"),
    ]

    operations = [
        migrations.AddField(
            model_name="narations",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
