# Generated by Django 4.2.5 on 2023-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_narations_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templist",
            name="serialno",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
