# Generated by Django 4.2.5 on 2023-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_alter_templist_serialno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("Debit", "Debit"), ("Credit", "Credit")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("amount", models.FloatField(null=True)),
                ("date", models.DateField(null=True)),
            ],
        ),
    ]
