# Generated by Django 4.2.5 on 2023-11-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="temp",
            name="brand",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
