# Generated by Django 4.2.5 on 2023-11-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0032_agents_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="unique_key",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
