# Generated by Django 4.2.5 on 2023-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_orders_unique_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="agents_records",
            name="random",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="random",
            field=models.IntegerField(null=True),
        ),
    ]
