# Generated by Django 4.2.5 on 2023-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_agents_records_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="total_amount",
            field=models.FloatField(null=True),
        ),
    ]
