# Generated by Django 4.1.12 on 2023-12-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0040_supplierorders_alter_orders_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="narations",
            name="order_type",
            field=models.CharField(
                choices=[("Debit", "Debit"), ("Credit", "Credit")],
                max_length=10,
                null=True,
            ),
        ),
    ]
