# Generated by Django 4.1.12 on 2023-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_rename_price_masterlist_bprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agents_records",
            name="refund_amound",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agents_records",
            name="sales_revenue",
            field=models.IntegerField(default=0),
        ),
    ]
