# Generated by Django 4.1.12 on 2023-12-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_agents_records_refund_amound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brpice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.stockout",
            ),
        ),
    ]
