# Generated by Django 4.1.12 on 2023-12-21 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_product_brpice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brpice",
        ),
    ]
