# Generated by Django 4.1.12 on 2023-12-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_remove_product_brpice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brpice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.stockout",
            ),
        ),
    ]
