# Generated by Django 4.1.12 on 2023-12-21 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_product_brpice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brpice",
            new_name="stockout",
        ),
    ]
