# Generated by Django 4.1.12 on 2023-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_rename_brpice_product_stockout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stockout",
        ),
        migrations.AddField(
            model_name="product",
            name="bprice",
            field=models.IntegerField(default=0),
        ),
    ]
