# Generated by Django 4.1.12 on 2023-12-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0049_accessory_accessorydesc"),
    ]

    operations = [
        migrations.AddField(
            model_name="temp",
            name="screen",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="templist",
            name="screen",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
