# Generated by Django 4.1.12 on 2024-01-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0050_temp_screen_templist_screen"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="bprice",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="accessory",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accessory",
            name="sprice",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="accessory",
            name="supplier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.vendor"
            ),
        ),
        migrations.DeleteModel(
            name="AccessoryDesc",
        ),
    ]
