# Generated by Django 5.0.1 on 2024-01-08 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0052_dcustomer_sales_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dcustomer",
            name="sales_agent",
        ),
    ]
